### ISSUE TITLE
Add support for power profiles

### ISSUE THREAD

**Issue by hertz1** [zuk-devs/android_device_zuk_msm8996-common#10]
According to [this commit](https://github.com/LineageOS/android_hardware_qcom_power/commit/c9f97d7e3dfff04fe6f524e2f0e9c7d67c810c3c#diff-0799925d8cb1da8045848c06f745d52c), power profiles for msm8996 was added in upstream LineageOS. Is it possible to enable it for our device?

**Comment by ghost** [comment]
Done (zuk-devs/android_device_zuk_msm8996-common@161230f307e6e612ffb12ca3f551a9353596e15c)
