### ISSUE TITLE
error with data-ipa-cfg-mgr

### ISSUE THREAD

**Issue by dev-kasibhatla** [zuk-devs/android_device_zuk_msm8996-common#12]
my build always fails giving errors for illegal struct declarations in data-ipa-cfg-mgr.
for example:

`error: declaration of 'struct ipa_ioc_nat_pdn_entry' will not be visible outside of this function [-Werror,-Wvisibility]
int ipa_nati_modify_pdn(struct ipa_ioc_nat_pdn_entry *entry);
                               ^
device/zuk/msm8996-common/data-ipa-cfg-mgr/ipanat/src/ipa_nat_drv.c:190:31: error: variable has incomplete type 'struct ipa_ioc_nat_pdn_entry'
        struct ipa_ioc_nat_pdn_entry pdn_data;
                                     ^
device/zuk/msm8996-common/data-ipa-cfg-mgr/ipanat/src/ipa_nat_drv.c:190:9: note: forward declaration of 'struct ipa_ioc_nat_pdn_entry'
        struct ipa_ioc_nat_pdn_entry pdn_data;
               ^
device/zuk/msm8996-common/data-ipa-cfg-mgr/ipanat/src/ipa_nat_drv.c:202:18: error: use of undeclared identifier 'IPA_MAX_PDN_NUM'
        if (pdn_index > IPA_MAX_PDN_NUM) {
`
i get several of these.

**Comment by ghost** [comment]
I need more info:

* Which branch are you building?
* Do you still have that problem with the latest commits for data-ipa-cfg-mgr?

**Comment by dev-kasibhatla** [comment]
I was building 8.1 for lineage and the build completed successfully. 
I replaced that file with the file from my lineage 14.1 tree and things seem to work fine.
Thanks a lot.
