### ISSUE TITLE
sepolicy: location: unknown type wcnss_prop

### ISSUE THREAD

**Issue by faizauthar12** [zuk-devs/android_device_zuk_msm8996-common#14]
https://github.com/zuk-devs/android_device_zuk_msm8996-common/blob/6add266a22933d6e038913d7e70f02e09c4ac792/sepolicy/location.te#L3

```
device/zuk/msm8996-common/sepolicy/location.te:4:ERROR 'unknown type wcnss_prop' at token ';' on line 74403:
allow location sysfs_soc:dir search;
allow location wcnss_prop:file { getattr open read ioctl lock map };
checkpolicy:  error(s) encountered while parsing configuration
```

**Comment by DD3Boh** [comment]
Being a global thing, better to declare this globally like LineageOS is doing here:

**Comment by DD3Boh** [comment]
Being it a global thing, better to declare it globally like Lineage's doing here:
https://review.lineageos.org/c/LineageOS/android_device_qcom_sepolicy/+/228570

If we added this to the device tree once the commit will get merged we'll have issues.
