### ISSUE TITLE
zukperf:translation for zh-rCN

### ISSUE THREAD

**Issue by RuRuTiaSaMa** [zuk-devs/android_device_zuk_msm8996-common#18]
<?xml version="1.0" encoding="utf-8"?>

<resources xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2">

    <string name="zukpref_title">ZUK Extras</string>
    <string name="zuk_gestures_summary">显示颜色校准</string>
	
    
    <string name="graphics_title">图像</string>

    <string name="kcal_title">显示颜色</string>
    <string name="kcal_summary">使用KCAL进行显示颜色校准</string>
    <string name="kcal_enabled_title">启用 KCAL</string>
    <string name="kcal_enabled_summary">启用KCAL进行显示颜色校准</string>
    <string name="kcal_red">红</string>
    <string name="kcal_green">绿</string>
    <string name="kcal_blue">蓝</string>
    <string name="kcal_saturation">饱和度</string>
    <string name="kcal_contrast">对比度</string>
    <string name="menu_reset">重置</string>
    <string name="kcal_color_temp">色温 (K)</string>	

</resources>

**Comment by libxzr** [comment]
You should open a pull request instead of issue.:joy:

**Comment by RuRuTiaSaMa** [comment]
> You should open a pull request instead of issue.



> You should open a pull request instead of issue.

I did not bring this commit in my own copy forked from here
